name: icon-theme-colloid
build-base: core24
base: bare
version: '2025-06-24'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Colloid icon theme
description: |
  A Snap that allows you to use Colloid icon themes in Snap apps
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Colloid-cursors
        - $SNAP/share/icons/Colloid-dark-cursors
        - $SNAP/share/icons/Colloid
        - $SNAP/share/icons/Colloid-Catppuccin
        - $SNAP/share/icons/Colloid-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Dark
        - $SNAP/share/icons/Colloid-Dracula
        - $SNAP/share/icons/Colloid-Dracula-Dark
        - $SNAP/share/icons/Colloid-Dracula-Light
        - $SNAP/share/icons/Colloid-Everforest
        - $SNAP/share/icons/Colloid-Everforest-Dark
        - $SNAP/share/icons/Colloid-Everforest-Light
        - $SNAP/share/icons/Colloid-Green
        - $SNAP/share/icons/Colloid-Green-Catppuccin
        - $SNAP/share/icons/Colloid-Green-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Green-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Green-Dark
        - $SNAP/share/icons/Colloid-Green-Dracula
        - $SNAP/share/icons/Colloid-Green-Dracula-Dark
        - $SNAP/share/icons/Colloid-Green-Dracula-Light
        - $SNAP/share/icons/Colloid-Green-Everforest
        - $SNAP/share/icons/Colloid-Green-Everforest-Dark
        - $SNAP/share/icons/Colloid-Green-Everforest-Light
        - $SNAP/share/icons/Colloid-Green-Gruvbox
        - $SNAP/share/icons/Colloid-Green-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Green-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Green-Light
        - $SNAP/share/icons/Colloid-Green-Nord
        - $SNAP/share/icons/Colloid-Green-Nord-Dark
        - $SNAP/share/icons/Colloid-Green-Nord-Light
        - $SNAP/share/icons/Colloid-Grey
        - $SNAP/share/icons/Colloid-Grey-Catppuccin
        - $SNAP/share/icons/Colloid-Grey-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Grey-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Grey-Dark
        - $SNAP/share/icons/Colloid-Grey-Dracula
        - $SNAP/share/icons/Colloid-Grey-Dracula-Dark
        - $SNAP/share/icons/Colloid-Grey-Dracula-Light
        - $SNAP/share/icons/Colloid-Grey-Everforest
        - $SNAP/share/icons/Colloid-Grey-Everforest-Dark
        - $SNAP/share/icons/Colloid-Grey-Everforest-Light
        - $SNAP/share/icons/Colloid-Grey-Gruvbox
        - $SNAP/share/icons/Colloid-Grey-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Grey-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Grey-Light
        - $SNAP/share/icons/Colloid-Grey-Nord
        - $SNAP/share/icons/Colloid-Grey-Nord-Dark
        - $SNAP/share/icons/Colloid-Grey-Nord-Light
        - $SNAP/share/icons/Colloid-Gruvbox
        - $SNAP/share/icons/Colloid-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Light
        - $SNAP/share/icons/Colloid-Nord
        - $SNAP/share/icons/Colloid-Nord-Dark
        - $SNAP/share/icons/Colloid-Nord-Light
        - $SNAP/share/icons/Colloid-Orange
        - $SNAP/share/icons/Colloid-Orange-Catppuccin
        - $SNAP/share/icons/Colloid-Orange-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Orange-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Orange-Dark
        - $SNAP/share/icons/Colloid-Orange-Dracula
        - $SNAP/share/icons/Colloid-Orange-Dracula-Dark
        - $SNAP/share/icons/Colloid-Orange-Dracula-Light
        - $SNAP/share/icons/Colloid-Orange-Everforest
        - $SNAP/share/icons/Colloid-Orange-Everforest-Dark
        - $SNAP/share/icons/Colloid-Orange-Everforest-Light
        - $SNAP/share/icons/Colloid-Orange-Gruvbox
        - $SNAP/share/icons/Colloid-Orange-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Orange-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Orange-Light
        - $SNAP/share/icons/Colloid-Orange-Nord
        - $SNAP/share/icons/Colloid-Orange-Nord-Dark
        - $SNAP/share/icons/Colloid-Orange-Nord-Light
        - $SNAP/share/icons/Colloid-Pink
        - $SNAP/share/icons/Colloid-Pink-Catppuccin
        - $SNAP/share/icons/Colloid-Pink-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Pink-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Pink-Dark
        - $SNAP/share/icons/Colloid-Pink-Dracula
        - $SNAP/share/icons/Colloid-Pink-Dracula-Dark
        - $SNAP/share/icons/Colloid-Pink-Dracula-Light
        - $SNAP/share/icons/Colloid-Pink-Everforest
        - $SNAP/share/icons/Colloid-Pink-Everforest-Dark
        - $SNAP/share/icons/Colloid-Pink-Everforest-Light
        - $SNAP/share/icons/Colloid-Pink-Gruvbox
        - $SNAP/share/icons/Colloid-Pink-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Pink-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Pink-Light
        - $SNAP/share/icons/Colloid-Pink-Nord
        - $SNAP/share/icons/Colloid-Pink-Nord-Dark
        - $SNAP/share/icons/Colloid-Pink-Nord-Light
        - $SNAP/share/icons/Colloid-Purple
        - $SNAP/share/icons/Colloid-Purple-Catppuccin
        - $SNAP/share/icons/Colloid-Purple-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Purple-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Purple-Dark
        - $SNAP/share/icons/Colloid-Purple-Dracula
        - $SNAP/share/icons/Colloid-Purple-Dracula-Dark
        - $SNAP/share/icons/Colloid-Purple-Dracula-Light
        - $SNAP/share/icons/Colloid-Purple-Everforest
        - $SNAP/share/icons/Colloid-Purple-Everforest-Dark
        - $SNAP/share/icons/Colloid-Purple-Everforest-Light
        - $SNAP/share/icons/Colloid-Purple-Gruvbox
        - $SNAP/share/icons/Colloid-Purple-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Purple-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Purple-Light
        - $SNAP/share/icons/Colloid-Purple-Nord
        - $SNAP/share/icons/Colloid-Purple-Nord-Dark
        - $SNAP/share/icons/Colloid-Purple-Nord-Light
        - $SNAP/share/icons/Colloid-Red
        - $SNAP/share/icons/Colloid-Red-Catppuccin
        - $SNAP/share/icons/Colloid-Red-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Red-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Red-Dark
        - $SNAP/share/icons/Colloid-Red-Dracula
        - $SNAP/share/icons/Colloid-Red-Dracula-Dark
        - $SNAP/share/icons/Colloid-Red-Dracula-Light
        - $SNAP/share/icons/Colloid-Red-Everforest
        - $SNAP/share/icons/Colloid-Red-Everforest-Dark
        - $SNAP/share/icons/Colloid-Red-Everforest-Light
        - $SNAP/share/icons/Colloid-Red-Gruvbox
        - $SNAP/share/icons/Colloid-Red-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Red-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Red-Light
        - $SNAP/share/icons/Colloid-Red-Nord
        - $SNAP/share/icons/Colloid-Red-Nord-Dark
        - $SNAP/share/icons/Colloid-Red-Nord-Light
        - $SNAP/share/icons/Colloid-Teal
        - $SNAP/share/icons/Colloid-Teal-Catppuccin
        - $SNAP/share/icons/Colloid-Teal-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Teal-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Teal-Dark
        - $SNAP/share/icons/Colloid-Teal-Dracula
        - $SNAP/share/icons/Colloid-Teal-Dracula-Dark
        - $SNAP/share/icons/Colloid-Teal-Dracula-Light
        - $SNAP/share/icons/Colloid-Teal-Everforest
        - $SNAP/share/icons/Colloid-Teal-Everforest-Dark
        - $SNAP/share/icons/Colloid-Teal-Everforest-Light
        - $SNAP/share/icons/Colloid-Teal-Gruvbox
        - $SNAP/share/icons/Colloid-Teal-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Teal-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Teal-Light
        - $SNAP/share/icons/Colloid-Teal-Nord
        - $SNAP/share/icons/Colloid-Teal-Nord-Dark
        - $SNAP/share/icons/Colloid-Teal-Nord-Light
        - $SNAP/share/icons/Colloid-Yellow
        - $SNAP/share/icons/Colloid-Yellow-Catppuccin
        - $SNAP/share/icons/Colloid-Yellow-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Yellow-Catppuccin-Light
        - $SNAP/share/icons/Colloid-Yellow-Dark
        - $SNAP/share/icons/Colloid-Yellow-Dracula
        - $SNAP/share/icons/Colloid-Yellow-Dracula-Dark
        - $SNAP/share/icons/Colloid-Yellow-Dracula-Light
        - $SNAP/share/icons/Colloid-Yellow-Everforest
        - $SNAP/share/icons/Colloid-Yellow-Everforest-Dark
        - $SNAP/share/icons/Colloid-Yellow-Everforest-Light
        - $SNAP/share/icons/Colloid-Yellow-Gruvbox
        - $SNAP/share/icons/Colloid-Yellow-Gruvbox-Dark
        - $SNAP/share/icons/Colloid-Yellow-Gruvbox-Light
        - $SNAP/share/icons/Colloid-Yellow-Light
        - $SNAP/share/icons/Colloid-Yellow-Nord
        - $SNAP/share/icons/Colloid-Yellow-Nord-Dark
        - $SNAP/share/icons/Colloid-Yellow-Nord-Light
parts:
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/icon-theme-colloid-snap/releases/download/2025-06-24/icon-theme-colloid-snap-files.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons
