name: icon-theme-colloid
build-base: core24
base: bare
adopt-info: icon-theme-colloid
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Colloid icon theme
description: |
  A Snap that allows you to use Colloid icon themes in Snap apps
grade: stable
confinement: strict
compression: lzo

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/usr/share/icons/Colloid-cursors
        - $SNAP/usr/share/icons/Colloid-dark-cursors
        - $SNAP/usr/share/icons/Colloid
        - $SNAP/usr/share/icons/Colloid-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Dark
        - $SNAP/usr/share/icons/Colloid-Dracula
        - $SNAP/usr/share/icons/Colloid-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Everforest
        - $SNAP/usr/share/icons/Colloid-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Green
        - $SNAP/usr/share/icons/Colloid-Green-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Green-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Green-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Dracula
        - $SNAP/usr/share/icons/Colloid-Green-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Green-Everforest
        - $SNAP/usr/share/icons/Colloid-Green-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Green-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Green-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Green-Light
        - $SNAP/usr/share/icons/Colloid-Green-Nord
        - $SNAP/usr/share/icons/Colloid-Green-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Green-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Grey
        - $SNAP/usr/share/icons/Colloid-Grey-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Grey-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Grey-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Dracula
        - $SNAP/usr/share/icons/Colloid-Grey-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Grey-Everforest
        - $SNAP/usr/share/icons/Colloid-Grey-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Grey-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Grey-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Grey-Light
        - $SNAP/usr/share/icons/Colloid-Grey-Nord
        - $SNAP/usr/share/icons/Colloid-Grey-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Grey-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Light
        - $SNAP/usr/share/icons/Colloid-Nord
        - $SNAP/usr/share/icons/Colloid-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Orange
        - $SNAP/usr/share/icons/Colloid-Orange-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Orange-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Orange-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Dracula
        - $SNAP/usr/share/icons/Colloid-Orange-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Orange-Everforest
        - $SNAP/usr/share/icons/Colloid-Orange-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Orange-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Orange-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Orange-Light
        - $SNAP/usr/share/icons/Colloid-Orange-Nord
        - $SNAP/usr/share/icons/Colloid-Orange-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Orange-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Pink
        - $SNAP/usr/share/icons/Colloid-Pink-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Pink-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Pink-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Dracula
        - $SNAP/usr/share/icons/Colloid-Pink-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Pink-Everforest
        - $SNAP/usr/share/icons/Colloid-Pink-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Pink-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Pink-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Pink-Light
        - $SNAP/usr/share/icons/Colloid-Pink-Nord
        - $SNAP/usr/share/icons/Colloid-Pink-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Pink-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Purple
        - $SNAP/usr/share/icons/Colloid-Purple-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Purple-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Purple-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Dracula
        - $SNAP/usr/share/icons/Colloid-Purple-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Purple-Everforest
        - $SNAP/usr/share/icons/Colloid-Purple-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Purple-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Purple-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Purple-Light
        - $SNAP/usr/share/icons/Colloid-Purple-Nord
        - $SNAP/usr/share/icons/Colloid-Purple-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Purple-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Red
        - $SNAP/usr/share/icons/Colloid-Red-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Red-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Red-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Dracula
        - $SNAP/usr/share/icons/Colloid-Red-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Red-Everforest
        - $SNAP/usr/share/icons/Colloid-Red-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Red-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Red-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Red-Light
        - $SNAP/usr/share/icons/Colloid-Red-Nord
        - $SNAP/usr/share/icons/Colloid-Red-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Red-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Teal
        - $SNAP/usr/share/icons/Colloid-Teal-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Teal-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Teal-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Dracula
        - $SNAP/usr/share/icons/Colloid-Teal-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Teal-Everforest
        - $SNAP/usr/share/icons/Colloid-Teal-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Teal-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Teal-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Teal-Light
        - $SNAP/usr/share/icons/Colloid-Teal-Nord
        - $SNAP/usr/share/icons/Colloid-Teal-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Teal-Nord-Light
        - $SNAP/usr/share/icons/Colloid-Yellow
        - $SNAP/usr/share/icons/Colloid-Yellow-Catppuccin
        - $SNAP/usr/share/icons/Colloid-Yellow-Catppuccin-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Catppuccin-Light
        - $SNAP/usr/share/icons/Colloid-Yellow-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Dracula
        - $SNAP/usr/share/icons/Colloid-Yellow-Dracula-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Dracula-Light
        - $SNAP/usr/share/icons/Colloid-Yellow-Everforest
        - $SNAP/usr/share/icons/Colloid-Yellow-Everforest-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Everforest-Light
        - $SNAP/usr/share/icons/Colloid-Yellow-Gruvbox
        - $SNAP/usr/share/icons/Colloid-Yellow-Gruvbox-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Gruvbox-Light
        - $SNAP/usr/share/icons/Colloid-Yellow-Light
        - $SNAP/usr/share/icons/Colloid-Yellow-Nord
        - $SNAP/usr/share/icons/Colloid-Yellow-Nord-Dark
        - $SNAP/usr/share/icons/Colloid-Yellow-Nord-Light
parts:
  icon-theme-colloid:
    plugin: nil
    source: https://github.com/vinceliuice/Colloid-icon-theme.git
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons
      ./install.sh --scheme all --theme all --notint --dest $CRAFT_PART_INSTALL/usr/share/icons
      mv -f cursors/dist $CRAFT_PART_INSTALL/usr/share/icons/Colloid-cursors
      mv -f cursors/dist-dark $CRAFT_PART_INSTALL/usr/share/icons/Colloid-dark-cursors
      craftctl set version=$(date +%Y-%m-%d)
    prime:
      - usr/share/icons
